Tidied up some of the Elm code.
3digitdev/verbly pull request #1
Opened 2019-10-24 14:22 UTC by wolfadex

- cleaning up `exposing (..)`
- added a couple function type definitions
- removed unused `Msg`s
- switch some `case String of ""` into `if then else`
- In `Translate.elm` line 246, use destructuring instead of `Tuple.first` and `Tuple.second`

2019-10-25 06:00 UTC, 3digitdev commented on src/elm/lib/Api.elm
> -    Result Http.Error ResponseObject
Deleting this and removing it from `exposing` causes the app to not compile.  This is needed for `Translate.elm`

2019-10-25 06:04 UTC, 3digitdev requested changes
Deleting this and removing it from `exposing` causes the app to not compile.  This is needed for `Translate.elm`

2019-10-25 06:04 UTC, 3digitdev commented on src/elm/lib/Api.elm
> -    Result Http.Error ResponseObject
Deleting this and removing it from `exposing` causes the app to not compile.  This is needed for `Translate.elm`

2019-10-25 13:43 UTC, wolfadex commented on src/elm/lib/Api.elm
> -    Result Http.Error ResponseObject
Added that back in

2019-10-26 00:36 UTC, 3digitdev approved these changes

2019-10-26 00:36 UTC, merged